"""Add is_wfh, lat, lon to Punch model

Revision ID: 8087438f0933
Revises: 
Create Date: 2025-05-22 10:08:16.914530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8087438f0933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wfh', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punch', schema=None) as batch_op:
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')
        batch_op.drop_column('is_wfh')

    # ### end Alembic commands ###
